spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
  h2:
    console:
      enabled: true
      path: /h2-console


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/foodly
          jwk-set-uri: http://localhost:8080/realms/foodly/protocol/openid-connect/certs
          
server:
    port: 8081

